POST http://localhost:3003/user/create 
Content-Type: application/json 

{    
    "name": "Alex",
    "email": "123@gmail.com",
    "password": "testando"
}

###
POST http://localhost:3003/post/create 
Content-Type: application/json 

{
    "id": "123",
    "createAt": "04/08/2022",
    "photo": "httppp...",
    "description": "ferias ferias",
    "type": "normal",
    "authorId" : "1"
}
